FROM node:20-alpine AS frontend

WORKDIR /usr/src/app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ .

WORKDIR /usr/src/app/frontend

RUN npm run build

FROM golang:1.23.0 AS go

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /clai ./cmd/clai

COPY --from=frontend /usr/src/app/dist ./frontend/dist

CMD ["/clai"]
